arb-dir: assets/l10n
output-dir: lib/src/common/localization/generated
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false
format: true